### PR TITLE
Added device classes and state classes

### PR DESCRIPTION
**Pull request by mmillmor**
Changed the sensors to have a state_class, and added missing device_classes
This allows for the sensors to be shown on dashboards and to have statistics gathered for the devices

### CODE REVIEW

**Comment by cytech** [comment]
this has already been implemented in v1.0.2
and Fixed in v1.1.0.
v1.1.0 will be released after HASS 2023.1.0

**Comment by mmillmor** [comment]
Thanks. I didn't spot that.

BTW, I took a look at the new code and one tiny change might help - make precipTotal total_increasing instead of measurement, because it increases and resets each day rather than being an instantaneous value that goes up and down

**Comment by cytech** [comment]
ok, will do
thanx

**Comment by cytech** [comment]
released
https://github.com/cytech/Home-Assistant-wundergroundpws/releases/tag/v1.1.0

**Pull request closed without merging**
