### PR TITLE
Weather entity

### PR DESCRIPTION
**Pull request by shtrom**
This should take care of #2.

Some of the mappings from the TWC observations and forecast data [0,1]
to HomeAssistant fields [2] are a bit quirky, but the core functionality
is here.

Note: Because of the split, the base configuration (API key and PWS ID) needs to be
placed in a separate section of the `configuration.yaml`, outside of the
`sensors` section:

	wundergroundpws:
	  api_key: YOUR_API_KEY
	  pws_id: YOUR_STATION_ID
	  numeric_precision: none

	sensor:
	  - platform: wundergroundpws
	    monitored_conditions:
              # dedicated sensors, separate from what's needed for the weather entity
	      - temp

[0] https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit
[1] https://docs.google.com/document/d/1KGb8bTVYRsNgljnNH67AMhckY8AQT2FVwZ9urj8SWBs/edit
[2] https://developers.home-assistant.io/docs/core/entity/weather/

### CODE REVIEW

**Comment by shtrom** [comment]
I just rebased on the latest version of the code, and retested.

@cytech What do you think of this? It works nicely.

Screenshot from 2022-11-27 22-54-26
Screenshot from 2022-11-27 22-54-36


Is there anything that would hold up merging this?

**Comment by cytech** [comment]
I think it looks great.
I had looked at this pr a week or so ago , but was unable to create the actual weather entity when merged.
All the sensors were created , but no weather entity for the card.
So, I decided to add  a config_flow  and make it a "real" integration prior to merging your changes.
I will try and get back to it in the next week or 2.
thanx

**Comment by shtrom** [comment]
On 28 November 2022 1:38:07 am AEDT, cytech ***@***.***> wrote:
>I think it looks great.
>I had looked at this pr a week or so ago , but was unable to create the actual weather entity when merged.
>All the sensors were created , but no weather entity for the card.
>So, I decided to add  a config_flow  and make it a "real" integration prior to merging your changes.
>I will try and get back to it in the next week or 2.
>thanx
>

Oh. Yeah, config flow would be great!

I'd recommend working off the tip of my branch, as it would be easier to merge due some of the refactors I did.

Weird that the weather entity didn't work out of the box. I did find a bug yesterday where it would fail when the pressure wasn't available. But it would be pretty obvious in the logs.
-- 
Olivier Mehani ***@***.***>
Sent from my mobile, please excuse my brevity.

**Comment by cytech** [comment]
I pulled down your weather-entity branch directly and set in custom components.
sensors are created. weather entity is not.
Tracing in debug never seems to call weather.py.
I have no idea why this is the case. There are no relevant errors in the logs.
the default open_meteo component works correctly but i can see nothing obvious as to what the problem is (open_meteo is hass default component with config_flow)

I reverted the merge so if you have any ideas and want to create a new pull request, please do.
thanx
dave

**Pull request merged**
