### PR TITLE
Weather entity

### PR DESCRIPTION
**Pull request by shtrom**
Continuing from #96.

### CODE REVIEW

**Comment by shtrom** [comment]
@cytech I pulled the code at the commit just before the revert and... everything works for me...

I'm wondering what the differences in setup are. What do you have in your `configuration.yaml`, and how do you run HomeAssistant to test?

It worked for me with Home Assistant 2022.3.6 (and 2022.11.4 just now) in Docker.
<details>
<summary>docker-compose.yaml</summary>

```yaml
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./Home-Assistant-wundergroundpws/www/wupws_icons:/config/www/wupws_iconsversion: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./Home-Assistant-wundergroundpws/www/wupws_icons:/config/www/wupws_icons
      - ./Home-Assistant-wundergroundpws/custom_components/wundergroundpws/:/config/custom_components/wundergroundpws
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```
</details>
<details>
<summary>configuration.yaml</summary>

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: warn
  logs:
    custom_components.wundergroundpws: debug

wundergroundpws:
  api_key: <key>
  pws_id: KCASANFR1708
  numeric_precision: decimal

weather:
  - platform: wundergroundpws

#sensor:
#  # https://github.com/cytech/Home-Assistant-wundergroundpws
#  - platform: wundergroundpws
#    monitored_conditions:
#      # Current conditions
#      - dewpt
#      - heatIndex
#      - precipRate
#      - precipTotal
#      - pressure
#      - solarRadiation
#      - temp
#      - uv
#      - windGust
#      - windSpeed
#      # Forecast
#      - precip_1d
#      - precip_chance_1d
#      - temp_high_1d
#      - temp_low_1d
#      - wind_1d
#      - weather_1d
#      - weather_1n

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```
</details>

**Comment by rudizl** [comment]
@shtrom: I`d like to test this, but I have a couple of questions. So you don`t add 
`monitored_conditions:
    - obsTimeLocal
    - solarRadiation
    - uv
    - winddir
    - humidity
    - dewpt
    - heatIndex
    - windChill
    - precipTotal
    - precipRate
    - pressure
    - temp
    - windGust
    - windSpeed
    - weather_1d
    - weather_1n
    - ...`
    at all? Also whete goes `lang: bg-BG` or whatever language code?

**Comment by shtrom** [comment]
@rudizl The Weather entity grabs the data straight out of the WUndergroundData object, and doesn't need the sensors. But you can add them nonetheless if you want.

I don't think the language is necessary.

Speaking of the sensors, @cytech, if you don't want to bring in the Weather entity until it works, the only commit to revert is https://github.com/shtrom/Home-Assistant-wundergroundpws/commit/4489e6acbda4dc40c07afd1043a4f22359044bb0; the others are a refactor to split out the API logic from the Sensor code, and is likely to be best done before the Config Flow work (if you haven't started yet), otherwise I think the changes will be at risk of conflicting.

**Comment by shtrom** [comment]
@cytech I realised I forgot to update the README when I was done 🤦🏼.

You also need
```
weather:
  - platform: wundergroundpws
```
in the config to enable the weather entity.

**Comment by rudizl** [comment]
@shtrom 
It's working almost perfectly :)
wu1
wu2
wu3
I only have issues with a few sensors. can you check if you included all these sensors?
`    - obsTimeLocal
    - solarRadiation
    - uv
    - winddir
    - humidity
    - dewpt
    - heatIndex
    - windChill
    - precipTotal
    - precipRate
    - pressure
    - temp
    - windGust
    - windSpeed
    - weather_1d
    - weather_1n
    - temp_high_1d
    - temp_low_1d
    - precip_1d
    - precip_chance_1d
    - wind_1d
    - temp_high_2d
    - temp_low_2d
    - precip_2d
    - precip_chance_2d
    - wind_2d
    - weather_2d
    - weather_2n
    - temp_high_3d
    - temp_low_3d
    - precip_3d
    - precip_chance_3d
    - wind_3d
    - weather_3d
    - weather_3n
    - temp_high_4d
    - temp_low_4d
    - precip_4d
    - precip_chance_4d
    - wind_4d
    - weather_4d
    - weather_4n
    - temp_high_5d
    - temp_low_5d
    - precip_5d
    - precip_chance_5d
    - wind_5d
    - weather_5d
    - weather_5n`
    Also language is needed for extended conditions. Now my card shows just cloudy or rainy. Can you check that too?
Anyway, perfect job!

**Comment by cytech** [comment]
knew it was something simple I was missing....
weather:
  - platform: wundergroundpws
 solves it.
Also, all sensor names in README need to be changed to lower case:
solarRadiation =  solarradiation
thanx

**Comment by rudizl** [comment]
This is about extended conditions:
https://api.weather.com/v3/wx/forecast/daily/5day?placeid=327145917e06d09373dd2760425a88622a62d248fd97550eb4883737d8d1173b&units=e&language=en-US&format=json&apiKey=yourApiKey 
Those texts are language dependent:
image

**Comment by shtrom** [comment]
@rudizl
* for the language, there is support for `wundergroundpws.lang` with the following supported values: https://github.com/cytech/Home-Assistant-wundergroundpws/pull/114/files#diff-e68e290b1a0596ffff45d5a20ef820091cc9f1a9b7f3d49b4d44bdea89add646R21-R28
 * however, there was a bug in the handling of the URL, so I fixed that
 * but that won't work well, because now all the extended conditions are in a different language, which is not supported by the map in https://github.com/cytech/Home-Assistant-wundergroundpws/pull/114/files#diff-2677f754c25742b16d6a6d8205ed621789f818944851170c4bbf294505db40bfR41-R109

So, we need the forecast in `en-US` so we can remap it to Home Assistant's standard weather conditions in https://github.com/home-assistant/core/blob/3ad4c9768cb454aec0b49ba8a472c80407ef4ac1/homeassistant/components/weather/__init__.py#L52-L67, but this creates the issue you highlighted where the narrative is not in the desired target language.

We could fix this by, e.g., querying the API twice (with and without language), but it's a bit ugly. I'd rather leave this as a bug for now, and circle back, if that's OK with @cytech.

PS: what's that weather card that shows all the narratives? The default I have doesn't seem to do it.

**Comment by shtrom** [comment]
Ok, I fixed a few more bugs in the forecast prediction. It now correctly maps `P Cloudy` and `M Cloudy` to `partlycloudy`. @rudizl this may fix you only getting cloudy or rainy.

I think this should all be good to go as a functional first cut.

**Comment by rudizl** [comment]
> PS: what's that weather card that shows all the narratives? The default I have doesn't seem to do it.

https://github.com/Makin-Things/platinum-weather-card

**Comment by rudizl** [comment]
After updating to the new version I have a couple of errors:
`Logger: homeassistant.components.weather
Source: custom_components/wundergroundpws/wunderground_data.py:174
Integration: Weather (documentation, issues)
First occurred: 17:40:48 (2 occurrences)
Last logged: 17:40:48

Error adding entities for domain weather with platform wundergroundpws
Error while setting up wundergroundpws platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 710, in state_attributes
    if self.forecast is not None:
  File "/config/custom_components/wundergroundpws/weather.py", line 168, in forecast
    forecast = [
  File "/config/custom_components/wundergroundpws/weather.py", line 170, in <listcomp>
    ATTR_FORECAST_CONDITION: self._rest._wxPhraseShort_to_conditio(
  File "/config/custom_components/wundergroundpws/wunderground_data.py", line 174, in _wxPhraseShort_to_conditio
    wx_phrase_short_clean = wx_phrase_short.replace(s, '')
AttributeError: 'NoneType' object has no attribute 'replace'`
`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:520
Integration: Sensor (documentation, issues)
First occurred: 17:40:48 (2 occurrences)
Last logged: 17:40:48

Platform wundergroundpws does not generate unique IDs. ID IVARNA85,weather_1d is already used by sensor.wupws_weather_1d - ignoring sensor.wupws_weather_1d
Platform wundergroundpws does not generate unique IDs. ID IVARNA85,weather_1n is already used by sensor.wupws_weather_1n - ignoring sensor.wupws_weather_1n`

`This error originated from a custom integration.

Logger: custom_components.wundergroundpws.wunderground_data
Source: custom_components/wundergroundpws/wunderground_data.py:182
Integration: Wundergroundpws (documentation, issues)
First occurred: 17:40:48 (1 occurrences)
Last logged: 17:40:48

Unsupported condition string "". Please update WUndergroundData.condition_map.`

**Comment by cytech** [comment]
@shtrom 
created a new branch with all your work to work from v1.X.X
https://github.com/cytech/Home-Assistant-wundergroundpws/tree/v1.X.X
everything looks great.
i had to add a couple conditions to the map - M Sunny, AM Showers, PM Showers.
Also change to native reverted sensor names to the original format (no longer lower case)
lets work off of this branch.
Thank you for all your hard work
Dave

**Comment by shtrom** [comment]
@rudizl ```Unsupported condition string "". Please update WUndergroundData.condition_map.``` This is because of the `lang` now being honoured, and triggering the issue I mentioned above. If you comment it out or set `lang: en-US` in your config, that bit should work.

@cytech 
> i had to add a couple conditions to the map - M Sunny, AM Showers, PM Showers.

I guess it goes on to show it's not very sunny where I am 🙄. Note that AM and PM should be stripped by https://github.com/cytech/Home-Assistant-wundergroundpws/pull/114/files#diff-2677f754c25742b16d6a6d8205ed621789f818944851170c4bbf294505db40bfR106-R113 and https://github.com/cytech/Home-Assistant-wundergroundpws/pull/114/files#diff-2677f754c25742b16d6a6d8205ed621789f818944851170c4bbf294505db40bfR173-R174, and be reduced to `Showers`, so you shouldn't have to add them specifically. Otherwise, there's a bug in the stripping code (which arguably is dodgy in the first place...).

**Comment by shtrom** [comment]
@rudizl I confirmed it's a `lang` issue. It seems that other languages only have empty `wxPhraseShort`, which is what the Weather Entity use to convert to Home Assistant Forecast. I pushed a new commit to prevent it dying, but that won't fix the issue for now.

**Comment by cytech** [comment]
@shtrom
created a new branch with all your work to work from v1.X.X
https://github.com/cytech/Home-Assistant-wundergroundpws/tree/v1.X.X
includes latest commits.
please fork this branch to do any future commits  and PRs off of this branch.
I can't keep up with all the merges on the master.
as to the AM Showers is mapped to rainy and I did not feel like screwing with it further.
the v1.X.X branch is functional and working so we can take it from there
thanx again and i am closing this PR

**Pull request closed without merging**
